wandb_version: 1

steps:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704801104.725121
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 5
      - 14
      - 16
      - 23
      4: 3.10.12
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
