language_token = {'France': 0,
                  'Italy': 1,
                  'Israel': 2,
                  'Austria': 3,
                  'Croatia': 4,
                  'Chile': 5,
                  'South Africa': 6,
                  'India': 7,
                  'China': 8,
                  'South Korea': 9,
                  'Denmark': 10,
                  'Mexico': 11,
                  'Poland': 12,
                  'Brazil': 13,
                  'Iran': 14,
                  'Singapore': 15,
                  'Portugal': 16,
                  'Trinidad and Tobago': 17,
                  'Russia': 18,
                  'Ireland': 19,
                  'Canada': 20,
                  'UK': 21,
                  'Germany': 22,
                  'Philippines': 23,
                  'Australia': 24,
                  'USA': 25,
                  'Norway': 26,
                  'Pakistan': 27,
                  'Sri Lanka': 28,
                  'Spain': 29,
                  'Switzerland': 30,
                  'New Zealand': 31,
                  'Sweden': 32,
                  'Sudan': 33,
                  'Netherlands': 34,
                  'Guyana': 35}
